### Get home data
GET http://localhost:3000/api/home

### Get all categories
GET http://localhost:3000/api/categories

### Get a single category info
GET http://localhost:3000/api/category/5fc270b37e047b1a44320ba6

### Get products by category id
GET http://localhost:3000/api/products?cat=5fc270b37e047b1a44320ba6

### Get products by category name
GET http://localhost:3000/api/products?catName=autos

### Get products by category id, between a price range
GET http://localhost:3000/api/products?cat=5fc270b37e047b1a44320ba6&minprice=13000&maxprice=14000

### Get products by category name, between a price range
GET http://localhost:3000/api/products?catName=autos&minprice=13000&maxprice=14000

### Get a single product info
GET http://localhost:3000/api/product/nlx7JuC9

### Get product comments
GET http://localhost:3000/api/comments/nlx7JuC9

